### ISSUE TITLE
Application plans show the system_name

### ISSUE THREAD

**Issue by ManfredBo** [kevprice83/3scale-Open-Banking-Portal#25]
for some reason all the 6 published application plans show the "System name" rather than the "Name." 
Can you please change? or tell me why that is?

**Comment by kevprice83** [comment]
yeah I have requested for you to change this back in your PR #24 was a mistake in my [commit](https://github.com/kevprice83/3scale-Open-Banking-Portal/pull/23/commits/0a1e5cb8d80bddc5ea1fbc1f1a25f093b050bd16)
